version: "3.8"

networks:
  librechat_network:
    driver: bridge

services:
  librechat:
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: unless-stopped
    env_file:
    - .env
    ports:
      - "127.0.0.1:3080:3080"
    depends_on:
      - mongo
      - rag_api
      - ollama
    volumes:
      - ./librechat.yaml:/app/librechat.yaml:ro
      - ${LOCAL_DOCS_PATH}:/app/docs
      - ${LOCAL_DATA_PATH}:/app/data
    networks:
      - librechat_network

  mongo:
    image: mongo:6
    restart: unless-stopped
    env_file:
    - .env
    volumes:
      - mongo_data:/data/db
    networks:
      - librechat_network

  # Встроенный RAG API LibreChat
  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    restart: unless-stopped
    env_file:
    - .env
    depends_on:
      - vectordb
      - ollama
    networks:
      - librechat_network

  # PostgreSQL + PGVector для RAG
  vectordb:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    env_file:
    - .env
    volumes:
      - vectordb_data:/var/lib/postgresql/data
    networks:
      - librechat_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${VECTORDB_USER} -d ${VECTORDB_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Ollama для эмбеддингов
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    env_file:
    - .env
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - librechat_network

volumes:
  mongo_data:
  vectordb_data:
  ollama_data:
